webtalk_init -webtalk_dir D:/Github/Project/DE1_Parking_assistant/top/top.sim/sim_1/behav/xsim/xsim.dir/tb_sensor_driver_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Apr 30 17:15:38 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "3320ad67-fb6a-4380-b12a-5f86cd55524d" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "af6013bb15414570a2af751c28966ed6" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "7" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Xeon(R) CPU E3-1220 v3 @ 3.10GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3093 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 s" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "70.09_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "14908_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3708537460 -regid "" -xml D:/Github/Project/DE1_Parking_assistant/top/top.sim/sim_1/behav/xsim/xsim.dir/tb_sensor_driver_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/Github/Project/DE1_Parking_assistant/top/top.sim/sim_1/behav/xsim/xsim.dir/tb_sensor_driver_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/Github/Project/DE1_Parking_assistant/top/top.sim/sim_1/behav/xsim/xsim.dir/tb_sensor_driver_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
